server:
  port: 8080

spring:
  application:
    name: api-gateway

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:task_engine}
    username: ${DB_USER:green_user}
    password: ${DB_PASSWORD:green_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # Architectural constraint: Protect DB from overload
      minimum-idle: 2
      connection-timeout: 30000 # 30 seconds
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 1800000 # 30 minutes
      register-mbeans: true

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate # We manage schema via init.sql / migrations, NOT Hibernate
    show-sql: false
    properties:
      hibernate:
        type:
          "[json_format_mapper]": com.greennode.api_gateway.utilities.CustomHibernateJsonFormatter

#   # RabbitMQ Configuration
#   rabbitmq:
#     host: ${MQ_HOST:localhost}
#     port: ${MQ_PORT:5672}
#     username: ${MQ_USER:green_user}
#     password: ${MQ_PASSWORD:green_password}
#     listener:
#       simple:
#         retry:
#           enabled: true
#           initial-interval: 1000ms
#           max-retries: 3
