debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=${RABBITMQ_USER:green_user}
debezium.sink.rabbitmq.connection.password=${RABBITMQ_PASSWORD:}
debezium.sink.rabbitmq.exchange=cdc.events
debezium.sink.rabbitmq.routingKey=job.requested.v1

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=${POSTGRES_USER:green_user}
debezium.source.database.password=${POSTGRES_PASSWORD:}
debezium.source.database.dbname=${POSTGRES_DB:task_engine}
debezium.source.topic.prefix=task_engine
debezium.source.plugin.name=pgoutput
debezium.source.publication.autocreate.mode=filtered
debezium.source.table.include.list=public.outbox_events

debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=3000

debezium.transforms=outbox
debezium.transforms.outbox.route.by.field=type
debezium.transforms.outbox.route.topic.replacement=job.requested.v1
debezium.transforms.outbox.table.expand.json.payload=true
debezium.transforms.outbox.table.field.event.id=event_id
debezium.transforms.outbox.table.field.event.key=aggregate_id
debezium.transforms.outbox.type=io.debezium.transforms.outbox.EventRouter

debezium.format.value=json
debezium.format.value.schemas.enable=false
debezium.format.key=json
debezium.format.key.schemas.enable=false
