debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.password=green_password
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=green_user
debezium.sink.rabbitmq.exchange=cdc.events
debezium.sink.rabbitmq.routingKey=task_engine.public.outbox_events
debezium.sink.type=rabbitmq
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.dbname=task_engine
debezium.source.database.hostname=postgres
debezium.source.database.password=green_password
debezium.source.database.port=5432
debezium.source.database.user=green_user
debezium.source.offset.flush.interval.ms=1000
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.plugin.name=pgoutput
debezium.source.publication.autocreate.mode=filtered
debezium.source.table.include.list=public.outbox_events
debezium.source.topic.prefix=task_engine

debezium.transforms=outbox,unwrap
debezium.transforms.outbox.route.by.field=aggregate_type
debezium.transforms.outbox.table.expand.json.payload=true
debezium.transforms.outbox.table.field.event.key=aggregate_id
debezium.transforms.outbox.table.field.event.timestamp=created_at
debezium.transforms.outbox.type=io.debezium.transforms.outbox.EventRouter
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.delete.tombstone.handling.mode=rewrite

debezium.format.value=json
debezium.format.value.schemas.enable=false
debezium.format.key=json
debezium.format.key.schemas.enable=false